workflows:
  build_and_deploy:
    name: Build and Deploy to GitHub Pages
    environment:
      flutter: stable
      env_groups:
        - repo_credentials
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build web
        script: |
          flutter build web --release --no-tree-shake-icons

      - name: Verify build output
        script: |
          if [ ! -d "build/web" ]; then
            echo "Build directory does not exist. Aborting."
            exit 1
          fi
          ls -la build/web

      - name: Configure Git
        script: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global credential.helper 'cache --timeout=3600'
          echo "https://$APP_PASSWORD:@github.com" > ~/.git-credentials
          git push "https://Icarus-conf:$APP_PASSWORD@github.com/fc_lang.git" --tags

      - name: Checkout web branch
        script: |
          git fetch --all
          if git show-ref --verify --quiet refs/heads/web-branch; then
            git checkout web-branch
          else
            git checkout -b web-branch
          fi

      - name: Copy built files to web branch
        script: |
          rm -rf *  # Clear the web branch directory
          cp -R build/web/* .
          git add .
          git commit -m "Update web branch with latest changes from main" || echo "No changes to commit"
          git push origin web-branch

      - name: Deploy to GitHub Pages
        script: |
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push --force origin gh-pages

artifacts:
  - build/web
