workflows:
  build_and_deploy:
    name: Build and Deploy to GitHub Pages
    environment:
      flutter: stable
      groups:
        - web_deploy  # Replace with the actual name of your environment variable group
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build web
        script: flutter build web --release --no-tree-shake-icons

      - name: Verify build output
        script: |
          if [ ! -d "build/web" ]; then
            echo "Build directory does not exist. Aborting."
            exit 1
          fi
          ls -la build/web

      - name: Configure Git
        script: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global credential.helper 'cache --timeout=120'
          echo "https://${GITHUB_TOKEN}:@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Checkout web branch
        script: |
          git fetch --all
          if git show-ref --verify --quiet refs/heads/web-branch; then
            git checkout web-branch
          else
            git checkout -b web-branch
          fi

      - name: Copy built files to web branch
        script: |
          rm -rf *  # Clear the web branch directory
          cp -R build/web/* .
          git add .
          git commit -m "Update web branch with latest changes from main"
          git push origin web-branch

      - name: Deploy to GitHub Pages
        script: |
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages

artifacts:
  - build/web
