workflows:
  build_and_deploy:
    name: Build and Deploy
    environment:
      variables:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    scripts:
      - name: Checkout repository
        script: |
          git config --global user.name "Icarus-conf"
          git config --global user.email "brain.m.config@gmail.com"
          git clone https://github.com/Icarus-conf/fc_lang.git
          cd fc_lang
          
      - name: Build Flutter App
        script: |
          flutter build web

      - name: Copy built files to web branch
        script: |
          git fetch origin
          git checkout web-branch
          cp -R build/web/* .
          git add .
          git commit -m "Deploy to web"
          git push https://$GITHUB_TOKEN@github.com/Icarus-conf/fc_lang.git web-branch
